import{getComponentById}from"./components.js";import{getSlotById}from"./slots.js";import{getSelectedComponent,getSlotComponent,isComponentDisabled,setSelectedComponent,setSlotComponent}from"./state.js";import type{ComponentId,SlotDefinition,SlotId}from"./types.js";
let dragged:ComponentId|null=null;let reportError:(message:string,slotId?:SlotId)=>void=()=>undefined;let refresh:()=>void=()=>undefined;
export function slotAcceptsComponent(slot:SlotDefinition,id:ComponentId):boolean{const component=getComponentById(id);return Boolean(slot.enabled&&component&&component.allowedSlotTypes.includes(slot.slotType)&&(slot.allowedComponentIds?.includes(id)??slot.allowedCategories?.includes(component.category)??false))}
export function placeComponent(slotId:SlotId,id:ComponentId):boolean{const slot=getSlotById(slotId),component=getComponentById(id);if(!slot||!component)return false;if(!slotAcceptsComponent(slot,id)){const accepted=(slot.allowedComponentIds??[]).map(x=>getComponentById(x)?.label??x).join(", ")||"no components";reportError(`${slot.label} does not accept ${component.label}. Accepted: ${accepted}.`,slotId);return false}if(isComponentDisabled(id)&&getSlotComponent(slotId)!==id){reportError(`${component.label} is already in use and is not reusable.`,slotId);return false}setSlotComponent(slotId,id);setSelectedComponent(null);reportError("",slotId);return true}
export function initializeDragAndDrop(onError:(message:string,slotId?:SlotId)=>void,onRefresh:()=>void):void{reportError=onError;refresh=onRefresh;const toolbox=document.getElementById("component-toolbox"),canvas=document.getElementById("architecture-canvas");if(!toolbox||!canvas)return;
toolbox.addEventListener("click",e=>{const card=(e.target as HTMLElement).closest<HTMLElement>(".component-card");if(!card||card.ariaDisabled==="true")return;e.stopPropagation();setSelectedComponent(card.dataset.componentId as ComponentId);highlight()});
toolbox.addEventListener("dragstart",e=>{const card=(e.target as HTMLElement).closest<HTMLElement>(".component-card");if(!card||card.ariaDisabled==="true"){e.preventDefault();return}dragged=card.dataset.componentId as ComponentId;e.dataTransfer?.setData("text/plain",dragged);highlight()});toolbox.addEventListener("dragend",()=>{dragged=null;clearHighlights()});
canvas.addEventListener("dragover",e=>{const el=(e.target as HTMLElement).closest<HTMLElement>(".drop-slot");if(el){e.preventDefault();el.classList.add("drag-over")}});canvas.addEventListener("dragleave",e=>(e.target as HTMLElement).closest<HTMLElement>(".drop-slot")?.classList.remove("drag-over"));canvas.addEventListener("drop",e=>{e.preventDefault();const el=(e.target as HTMLElement).closest<HTMLElement>(".drop-slot"),id=(e.dataTransfer?.getData("text/plain")||dragged)as ComponentId;if(el&&id)placeComponent(el.dataset.slotId??"",id);dragged=null;clearHighlights();refresh()});
canvas.addEventListener("click",e=>{const target=e.target as HTMLElement,remove=target.closest<HTMLButtonElement>("[data-remove-slot]");if(remove){setSlotComponent(remove.dataset.removeSlot??"",null);reportError("",remove.dataset.removeSlot);return}const el=target.closest<HTMLElement>(".drop-slot"),id=getSelectedComponent();if(el&&id){placeComponent(el.dataset.slotId??"",id);refresh()}});document.addEventListener("click",e=>{if(!(e.target as HTMLElement).closest(".component-card,.drop-slot")){setSelectedComponent(null);clearHighlights()}})}
function highlight():void{const id=dragged??getSelectedComponent();document.querySelectorAll<HTMLElement>(".drop-slot").forEach(el=>{const slot=getSlotById(el.dataset.slotId??"");el.classList.toggle("compatible",Boolean(id&&slot&&slotAcceptsComponent(slot,id)))})}function clearHighlights():void{document.querySelectorAll(".drop-slot").forEach(x=>x.classList.remove("compatible","drag-over"))}
